% File 'epi.cls' Class for EPIROB-2002 Proceedings
% by Hideki Kozima

\input{sab.cls}

\setlength\textheight     {250mm}
\setlength\textwidth      {170mm}
\setlength\oddsidemargin  {-4.5mm}
\setlength\evensidemargin {-4.5mm}
\setlength\topmargin      {-10mm}
\setlength\headsep        {0mm}
\setlength\headheight     {0mm}
\setlength\columnsep      { 8mm}


%\setlength\textheight     {243mm}
%\setlength\textwidth      {168mm}
%\setlength\oddsidemargin  {-4.5mm}
%\setlength\evensidemargin {-4.5mm}
%\setlength\topmargin      { 0mm}
%\setlength\headsep        {0mm}
%\setlength\headheight     {0mm}
%\setlength\columnsep      { 8mm}

% end of 'epi.cls'
